### ISSUE TITLE
Apply format fails when environment uses python 3 instead of python 2

### ISSUE THREAD

**Issue by SoilRos** [barisione/clang-format-hooks#22]
I usually have my environment set up so that python 3 is the default executable of python. However, the git-hook fails to recognize this and launch the format diff with the python 3 (although the script seems to be python 2).

Of course, I can set my local environment back to python 2 and it just works fine, but I just wonder if it's possible to find a correct python2 executable from the batch script? If so, it would be a nice small feature to add to the apply-format script.

**Comment by barisione** [comment]
Interesting, I didn't even think about it!

On my mac  (with `clang-format` 8.0 coming from Homebrew) I see that `clang-format-diff` should support both Python 2 and 3 (there's a `if sys.version_info.major >= 3: ...` check).
Same on Debian with the `clang-format-8` package.
On the Ubuntu VM I have around, there's an older 6.0 which doesn't have the check.

There's a chance that they will drop support for Python 2 at some point so I would not want to always force Python 2. Maybe I could check the version and force Python 2 if `clang-format` is old.
I will have a think about it.

Which distro do you use? What version of `clang-format` do you have? Is it installed manually or from your distro package?

Thanks!

**Comment by SoilRos** [comment]
Ah, in effect, it is about the `clang-format` version.
I was using a Debian 10 distro with clang-format version 7. 
```bash
 ~$ git commit                                                                            ✔  10021  13:41:07
  File "/usr/share/clang/clang-format-7/clang-format-diff.py", line 94
    print 'Formatting', filename
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Formatting', filename)?

The apply-format script failed.
```
I updated it to version 9 and it just worked fine with the python 3 environment!

Thanks!

**Comment by barisione** [comment]
As it's going to be less and less likely that people will have this problem as more distros get more recent clang-format, I won't fix it unless somebody complains loudly ;)
