### ISSUE TITLE
Invalid value for -style

### ISSUE THREAD

**Issue by Scorpio86** [barisione/clang-format-hooks#26]
pre-commit cannot set style with format file from "git config hooks.clangFormatDiffStyle".
I tried with use absolute path and relative path, both failed.
Could you help to find fix?

**Comment by mateuszzz88** [comment]
style accepts same value as clang-format. So you don't specify path to style file (`.clang-format`), you specify `file` or `llvm` or what have you. `file` means that `.clang-format` file will be found in closest enclosing directory.

**Comment by Scorpio86** [comment]
> style accepts same value as clang-format. So you don't specify path to style file (`.clang-format`), you specify `file` or `llvm` or what have you. `file` means that `.clang-format` file will be found in closest enclosing directory.

Yes, you are right, I knew how to set configuration file as style. 
Thank you.
